In [1]:
# Multiple Linear Regression

import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd
#Loading the dataset
dataset = pd.read_csv('employee.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,4].values



In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 5 columns):
Department         30 non-null object
WorkedHours        30 non-null int64
Certification      30 non-null int64
YearsExperience    30 non-null float64
Salary             30 non-null int64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.2+ KB


In [ ]:
#Dealing with categorical variables##From the scikit.preprocessing library we first import few classes

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X= LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
onehotencoder= OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()

# Removing the extra dummy variable
X = X[:, 1:]

#Splitting the data into Training Set and Test Set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.2,random_state=0)

#Normalizing the features

#from sklearn.preprocessingimport StandardScaler
#sc_X= StandardScaler()
#X_train= sc_X.fit_transform(X_train)
#X_test= sc_X.transform(X_test)

In [2]:
#Fitting Multiple Linear Regression to Training Set
from sklearn.linear_model import LinearRegression
mlrObj= LinearRegression()
mlrObj.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [3]:
#Predicting on the Test Set
y_pred= mlrObj.predict(X_test)

In [4]:
print(y_test)

[ 37731 122391  57081  63218 116969 109431]


In [5]:
print(y_pred)

[  43891.26902659  126961.49881403   62010.5455212    61270.23196485
  112780.99305321  106171.56595799]


In [8]:
#Backward Elimination
import statsmodels.formula.api as sm
X = np.append(arr=np.ones((30,1)).astype(int), values=X, axis=1)
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          2.30000000e+03,   0.00000000e+00,   1.10000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          2.10000000e+03,   1.00000000e+00,   1.30000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          2.10400000e+03,   2.00000000e+00,   1.50000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.20000000e+03,   1.00000000e+00,   2.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.25400000e+03,   2.00000000e+00,   2.20000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          1.23600000e+03,   1.00000000e+00,   2.90000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          1.45200000e+03,   2.00000000e+00,   3.00000000e+00],
       [  1.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          1.78900000e+03,   1.00000000e+00,   3.20000000e+00],


In [9]:
# Now according to Backward elimination we first need to fit a model with all variables
X_sig= X[:,[0,1,2,3,4,5]]
obj_OLS= sm.OLS(endog= y, exog= X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.961
Model:                            OLS   Adj. R-squared:                  0.952
Method:                 Least Squares   F-statistic:                     117.2
Date:                Sat, 23 Feb 2019   Prob (F-statistic):           4.71e-16
Time:                        13:16:23   Log-Likelihood:                -300.09
No. Observations:                  30   AIC:                             612.2
Df Residuals:                      24   BIC:                             620.6
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.146e+04   4689.376      4.576      0.000    1.18e+04    3.11e+04
x1         -1421.4255   2683.353     -0.530      0.601   -6959.595    4116.744
x2            92.8656   2735.524      0.034      0.973   -5552.978    5738.710
x3             3.3361      2.410      1.384      0.179      -1.637       8.310
x4          -423.7607   1282.271     -0.330      0.744   -3070.237    2222.716
x5          9437.2530    510.978     18.469      0.000    8382.645    1.05e+04
==============================================================================
Omnibus:                        2.020   Durbin-Watson:                   1.918
Prob(Omnibus):                  0.364   Jarque-Bera (JB):                1.629
Skew:                           0.414   Prob(JB):                        0.443
Kurtosis:                       2.214   Cond. No.                     8.00e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large,  8e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [11]:
# The summary function displays a table with p-values for all the variables. 
#Variable x2 has the highest p-value and needs to be removed.

X_sig= X[:,[0,1,3,4,5]]
obj_OLS= sm.OLS(endog= y, exog= X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.961
Model:                            OLS   Adj. R-squared:                  0.954
Method:                 Least Squares   F-statistic:                     152.6
Date:                Sat, 23 Feb 2019   Prob (F-statistic):           3.54e-17
Time:                        13:21:32   Log-Likelihood:                -300.09
No. Observations:                  30   AIC:                             610.2
Df Residuals:                      25   BIC:                             617.2
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.151e+04   4315.092      4.986      0.000    1.26e+04    3.04e+04
x1         -1466.4735   2285.214     -0.642      0.527   -6172.961    3240.014
x2             3.3230      2.331      1.426      0.166      -1.477       8.124
x3          -422.1845   1255.570     -0.336      0.739   -3008.079    2163.710
x4          9439.2110    497.467     18.975      0.000    8414.659    1.05e+04
==============================================================================
Omnibus:                        2.056   Durbin-Watson:                   1.918
Prob(Omnibus):                  0.358   Jarque-Bera (JB):                1.630
Skew:                           0.407   Prob(JB):                        0.443
Kurtosis:                       2.200   Cond. No.                     7.20e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.2e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [12]:
X_sig= X[:,[0,1,3,5]]
obj_OLS= sm.OLS(endog= y, exog= X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.956
Method:                 Least Squares   F-statistic:                     210.7
Date:                Sat, 23 Feb 2019   Prob (F-statistic):           2.35e-18
Time:                        13:24:22   Log-Likelihood:                -300.16
No. Observations:                  30   AIC:                             608.3
Df Residuals:                      26   BIC:                             613.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.122e+04   4154.694      5.108      0.000    1.27e+04    2.98e+04
x1         -1479.8541   2245.558     -0.659      0.516   -6095.665    3135.956
x2             3.3059      2.290      1.443      0.161      -1.402       8.014
x3          9336.1224    385.024     24.248      0.000    8544.694    1.01e+04
==============================================================================
Omnibus:                        2.340   Durbin-Watson:                   1.842
Prob(Omnibus):                  0.310   Jarque-Bera (JB):                1.662
Skew:                           0.375   Prob(JB):                        0.436
Kurtosis:                       2.124   Cond. No.                     7.04e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.04e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [13]:
X_sig= X[:,[0,3,5]]
obj_OLS= sm.OLS(endog= y, exog= X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.960
Model:                            OLS   Adj. R-squared:                  0.957
Method:                 Least Squares   F-statistic:                     322.5
Date:                Sat, 23 Feb 2019   Prob (F-statistic):           1.42e-19
Time:                        13:26:39   Log-Likelihood:                -300.41
No. Observations:                  30   AIC:                             606.8
Df Residuals:                      27   BIC:                             611.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.102e+04   4099.682      5.127      0.000    1.26e+04    2.94e+04
x1             3.1236      2.250      1.389      0.176      -1.492       7.739
x2          9340.2046    380.920     24.520      0.000    8558.621    1.01e+04
==============================================================================
Omnibus:                        1.451   Durbin-Watson:                   1.842
Prob(Omnibus):                  0.484   Jarque-Bera (JB):                1.323
Skew:                           0.388   Prob(JB):                        0.516
Kurtosis:                       2.325   Cond. No.                     7.01e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.01e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [14]:
X_sig= X[:,[0,1,5]]
obj_OLS= sm.OLS(endog= y, exog= X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.954
Method:                 Least Squares   F-statistic:                     302.8
Date:                Sat, 23 Feb 2019   Prob (F-statistic):           3.22e-19
Time:                        13:26:53   Log-Likelihood:                -301.31
No. Observations:                  30   AIC:                             608.6
Df Residuals:                      27   BIC:                             612.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.615e+04   2420.521     10.802      0.000    2.12e+04    3.11e+04
x1         -1088.3419   2273.413     -0.479      0.636   -5753.000    3576.316
x2          9451.6710    384.095     24.608      0.000    8663.574    1.02e+04
==============================================================================
Omnibus:                        2.692   Durbin-Watson:                   1.654
Prob(Omnibus):                  0.260   Jarque-Bera (JB):                1.686
Skew:                           0.338   Prob(JB):                        0.430
Kurtosis:                       2.056   Cond. No.                         15.3
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
X_sig= X[:,[0,5]]
obj_OLS= sm.OLS(endog= y, exog= X_sig).fit()
obj_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.957
Model:                            OLS   Adj. R-squared:                  0.955
Method:                 Least Squares   F-statistic:                     622.5
Date:                Sat, 23 Feb 2019   Prob (F-statistic):           1.14e-20
Time:                        13:27:17   Log-Likelihood:                -301.44
No. Observations:                  30   AIC:                             606.9
Df Residuals:                      28   BIC:                             609.7
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.579e+04   2273.053     11.347      0.000    2.11e+04    3.04e+04
x1          9449.9623    378.755     24.950      0.000    8674.119    1.02e+04
==============================================================================
Omnibus:                        2.140   Durbin-Watson:                   1.648
Prob(Omnibus):                  0.343   Jarque-Bera (JB):                1.569
Skew:                           0.363   Prob(JB):                        0.456
Kurtosis:                       2.147   Cond. No.                         13.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [16]:
# Now the p-values are all less than 0.05

#Splitting the data into Training Set and Test Set
X_sig_train, X_sig_test, y_sig_train, y_sig_test= train_test_split(X_sig, y, test_size=0.2,random_state=0)
mlrObj_sig= LinearRegression()
mlrObj_sig.fit(X_sig_train, y_sig_train)
y_sig_pred= mlrObj_sig.predict(X_sig_test)

In [17]:
y_sig_pred

array([  40748.96184072,  122699.62295594,   64961.65717022,
         63099.14214487,  115249.56285456,  107799.50275317])

In [18]:
y_test

array([ 37731, 122391,  57081,  63218, 116969, 109431], dtype=int64)

In [20]:
y_pred

array([  43891.26902659,  126961.49881403,   62010.5455212 ,
         61270.23196485,  112780.99305321,  106171.56595799])

import statsmodels.formula.api as sm

def backwardElimination(x, sl):
    numVars= len(x[0])
    for i in range(0, numVars):
        obj_OLS= sm.OLS(y, x).fit()
        maxVar= max(obj_OLS.pvalues).astype(float)
        if maxVar> sl:
            for j in range(0, numVars-i):
                if (obj_OLS.pvalues[j].astype(float) == maxVar):
                    x = np.delete(x, j, 1)
                    obj_OLS.summary()
    return x

SL = 0.05
X_sig= X[:, [0, 1, 2, 3, 4, 5]]
X_Modeled= backwardElimination(X_sig, SL)